Display List properly, left with Status bar colour
AY2223S2-CS2103T-T12-2/tp pull request #121
Opened 2023-03-21 11:21 UTC by daytona65

Need to figure out the css for status bar...
Otherwise list displays as expected

2023-03-21 11:29 UTC, KSunil2001 commented on src/main/resources/view/HelpWindow.css
According to code style, is it okay to add single line comments the way you did? 🤔

2023-03-21 11:29 UTC, KSunil2001 commented on src/main/resources/view/PatientListCard.fxml
> +        <Label fx:id="status" styleClass="status-bar-with-border"/>
Does status not require a text field?

2023-03-21 13:34 UTC, yitong241 requested changes
Should a field be added for status?

2023-03-21 13:34 UTC, yitong241 commented on src/main/resources/view/MedInfoTheme.css
> +
decent color I like it

2023-03-21 13:34 UTC, yitong241 commented on src/main/resources/view/PatientListCard.fxml
> +        <Label fx:id="status" styleClass="status-bar-with-border"/>
same question

2023-03-21 14:28 UTC, daytona65 commented on src/main/resources/view/PatientListCard.fxml
> +        <Label fx:id="status" styleClass="status-bar-with-border"/>
No need because I set it in the java file

2023-03-21 14:28 UTC, daytona65 commented on src/main/resources/view/PatientListCard.fxml
> +        <Label fx:id="status" styleClass="status-bar-with-border"/>
By default it is an empty text field anyway

2023-03-22 03:46 UTC, daytona65 commented on src/main/resources/view/HelpWindow.css
I followed what the original authors did for Extensions.css, they did single line comments there too
No Idea if that's right

2023-03-22 03:51 UTC, daytona65 commented
> Should a field be added for status?

What do you mean

2023-03-22 09:48 UTC, nramapurath commented on src/main/java/seedu/address/ui/PatientCard.java
> +        String statusString = patient.getStatus().getDesc();
Isn't this a violation of law of demeter? Maybe you can consider adding a getStatusDescription method in patient?

2023-03-22 09:48 UTC, nramapurath commented on src/main/resources/view/Extensions.css
> +    -fx-text-fill: #d06651 !important;
Just curious, why did you choose to remove the rationale in the comments?

2023-03-23 03:50 UTC, daytona65 commented on src/main/java/seedu/address/ui/PatientCard.java
> +        String statusString = patient.getStatus().getDesc();
Alright sounds good, will do that

2023-03-23 03:52 UTC, merged